name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install modules
        run: python -m pip install youtube_dl
      - name: Download
        run: |
          youtube-dl --config-location config.txt
      - name: Upload
        run: |
          curl -sL https://git.io/file-transfer | sh
          ./transfer wet /downloads/
